# Generated by Django 5.0.6 on 2024-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cetagory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('is_completed', models.BooleanField()),
                ('Task_Assign_Date', models.DateField()),
                ('cetagory', models.ManyToManyField(to='cetagory_app.task_cetagory')),
            ],
        ),
    ]
